question_data = [{"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "In golf, what name is given to a hole score of two under par?",
                  "correct_answer": "Eagle",
                  "incorrect_answers": ["Birdie", "Bogey", "Albatross"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "Which player holds the NHL record of 2,857 points?",
                  "correct_answer": "Wayne Gretzky",
                  "incorrect_answers": ["Mario Lemieux ", "Sidney Crosby",
                                        "Gordie Howe"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "When was the first official international game played?",
                  "correct_answer": "1872",
                  "incorrect_answers": ["1880", "1863", "1865"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "Which city did the former NHL team &quot;The Nordiques&quot; originiate from?",
                  "correct_answer": "Quebec City",
                  "incorrect_answers": ["Houston", "Montreal", "New York"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "What team won the 2016 MLS Cup?",
                  "correct_answer": "Seattle Sounders",
                  "incorrect_answers": ["Colorado Rapids", "Toronto FC",
                                        "Montreal Impact"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "Who won the 2017 Formula One World Drivers&#039; Championship?",
                  "correct_answer": "Lewis Hamilton",
                  "incorrect_answers": ["Sebastian Vettel", "Nico Rosberg",
                                        "Max Verstappen"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "What is the most common type of pitch thrown by pitchers in baseball?",
                  "correct_answer": "Fastball",
                  "incorrect_answers": ["Slowball", "Screwball", "Palmball"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "Which country will host the 2022 FIFA World Cup?",
                  "correct_answer": "Qatar",
                  "incorrect_answers": ["USA", "Japan", "Switzerland"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "Who won the premier league title in the 2015-2016 season following a fairy tale run?",
                  "correct_answer": "Leicester City",
                  "incorrect_answers": ["Tottenham Hotspur", "Watford", "Stoke City"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "Which team has won the most Stanley Cups in the NHL?",
                  "correct_answer": "Montreal Canadians",
                  "incorrect_answers": ["Chicago Blackhawks", "Toronto Maple Leafs",
                                        "Detroit Red Wings"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "Who won the 2015 Formula 1 World Championship?",
                  "correct_answer": "Lewis Hamilton",
                  "incorrect_answers": ["Nico Rosberg", "Sebastian Vettel",
                                        "Jenson Button"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "Who won the UEFA Champions League in 2016?",
                  "correct_answer": "Real Madrid C.F.",
                  "incorrect_answers": ["FC Bayern Munich", "Atletico Madrid",
                                        "Manchester City F.C."]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "Which country will host the 2020 Summer Olympics?",
                  "correct_answer": "Japan",
                  "incorrect_answers": ["China", "Australia", "Germany"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "In bowling, what is the term used for getting three consecutive strikes?",
                  "correct_answer": "Turkey",
                  "incorrect_answers": ["Flamingo", "Birdie", "Eagle"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "Which team won 2014 FIFA World Cup in Brazil?",
                  "correct_answer": "Germany",
                  "incorrect_answers": ["Argentina", "Brazil", "Netherlands"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "In the 2014 FIFA World Cup, what was the final score in the match Brazil - Germany?",
                  "correct_answer": "1-7", "incorrect_answers": ["1-5", "1-6", "2-6"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "Which team won the 2015-16 English Premier League?",
                  "correct_answer": "Leicester City",
                  "incorrect_answers": ["Liverpool", "Cheslea", "Manchester United"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "What was the final score of the Germany vs. Brazil 2014 FIFA World Cup match?",
                  "correct_answer": "7 - 1",
                  "incorrect_answers": ["0 - 1", "3 - 4", "16 - 0"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "Who won the UEFA Champions League in 2017?",
                  "correct_answer": "Real Madrid C.F.",
                  "incorrect_answers": ["Atletico Madrid", "AS Monaco FC",
                                        "Juventus F.C."]},
                 {"type": "multiple", "difficulty": "easy", "category": "Sports",
                  "question": "In baseball, how many fouls are an out?",
                  "correct_answer": "0", "incorrect_answers": ["5", "3", "2"]}]
